//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.31 at 10:22:21 AM CST 
//


package com.amdocs.dashboard.mobile.xyChart;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for formatterSetElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="formatterSetElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="formatter" type="{http://www.amdocs.com/dashboard/mobile/XYChart}formatterElement"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "formatterSetElement", propOrder = {
    "formatter"
})
public class FormatterSetElement {

    protected List<FormatterElement> formatter;

    /**
     * Gets the value of the formatter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formatter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormatter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormatterElement }
     * 
     * 
     */
    public List<FormatterElement> getFormatter() {
        if (formatter == null) {
            formatter = new ArrayList<FormatterElement>();
        }
        return this.formatter;
    }

    public boolean isSetFormatter() {
        return ((this.formatter!= null)&&(!this.formatter.isEmpty()));
    }

    public void unsetFormatter() {
        this.formatter = null;
    }

}
