//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 12:51:18 AM CST 
//


package com.amdocs.dashboard.mobile.xyChart;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lineSeriesElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lineSeriesElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.amdocs.com/dashboard/mobile/XYChart}seriesElement">
 *       &lt;attribute name="lineColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="lineAlpha" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="lineWidth" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lineSeriesElement")
public class LineSeriesElement
    extends SeriesElement
{

    @XmlAttribute
    protected String lineColor;
    @XmlAttribute
    protected Float lineAlpha;
    @XmlAttribute
    protected Float lineWidth;

    /**
     * Gets the value of the lineColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineColor() {
        return lineColor;
    }

    /**
     * Sets the value of the lineColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineColor(String value) {
        this.lineColor = value;
    }

    public boolean isSetLineColor() {
        return (this.lineColor!= null);
    }

    /**
     * Gets the value of the lineAlpha property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getLineAlpha() {
        return lineAlpha;
    }

    /**
     * Sets the value of the lineAlpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setLineAlpha(float value) {
        this.lineAlpha = value;
    }

    public boolean isSetLineAlpha() {
        return (this.lineAlpha!= null);
    }

    public void unsetLineAlpha() {
        this.lineAlpha = null;
    }

    /**
     * Gets the value of the lineWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getLineWidth() {
        return lineWidth;
    }

    /**
     * Sets the value of the lineWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setLineWidth(float value) {
        this.lineWidth = value;
    }

    public boolean isSetLineWidth() {
        return (this.lineWidth!= null);
    }

    public void unsetLineWidth() {
        this.lineWidth = null;
    }

}
