//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.31 at 10:22:21 AM CST 
//


package com.amdocs.dashboard.mobile.xyChart;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lineSetElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lineSetElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="lineSeries" type="{http://www.amdocs.com/dashboard/mobile/XYChart}lineSeriesElement" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.amdocs.com/dashboard/mobile/XYChart}chartType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lineSetElement", propOrder = {
    "lineSeries"
})
public class LineSetElement {

    protected List<LineSeriesElement> lineSeries;
    @XmlAttribute
    protected ChartType type;

    /**
     * Gets the value of the lineSeries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineSeries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineSeries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineSeriesElement }
     * 
     * 
     */
    public List<LineSeriesElement> getLineSeries() {
        if (lineSeries == null) {
            lineSeries = new ArrayList<LineSeriesElement>();
        }
        return this.lineSeries;
    }

    public boolean isSetLineSeries() {
        return ((this.lineSeries!= null)&&(!this.lineSeries.isEmpty()));
    }

    public void unsetLineSeries() {
        this.lineSeries = null;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ChartType }
     *     
     */
    public ChartType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChartType }
     *     
     */
    public void setType(ChartType value) {
        this.type = value;
    }

    public boolean isSetType() {
        return (this.type!= null);
    }

}
