//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.04 at 10:50:59 AM CDT 
//


package com.amdocs.dashboard.mobile.xyChart;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.amdocs.dashboard.mobile.xyChart package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _XYChart_QNAME = new QName("http://www.amdocs.com/dashboard/mobile/XYChart", "XYChart");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.amdocs.dashboard.mobile.xyChart
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SeriesElement }
     * 
     */
    public SeriesElement createSeriesElement() {
        return new SeriesElement();
    }

    /**
     * Create an instance of {@link SeriesSetElement }
     * 
     */
    public SeriesSetElement createSeriesSetElement() {
        return new SeriesSetElement();
    }

    /**
     * Create an instance of {@link LineSeriesElement }
     * 
     */
    public LineSeriesElement createLineSeriesElement() {
        return new LineSeriesElement();
    }

    /**
     * Create an instance of {@link ServiceElement }
     * 
     */
    public ServiceElement createServiceElement() {
        return new ServiceElement();
    }

    /**
     * Create an instance of {@link AxisSetElement }
     * 
     */
    public AxisSetElement createAxisSetElement() {
        return new AxisSetElement();
    }

    /**
     * Create an instance of {@link ServiceParam }
     * 
     */
    public ServiceParam createServiceParam() {
        return new ServiceParam();
    }

    /**
     * Create an instance of {@link FormatterElement }
     * 
     */
    public FormatterElement createFormatterElement() {
        return new FormatterElement();
    }

    /**
     * Create an instance of {@link AxisElement }
     * 
     */
    public AxisElement createAxisElement() {
        return new AxisElement();
    }

    /**
     * Create an instance of {@link XYChartElement }
     * 
     */
    public XYChartElement createXYChartElement() {
        return new XYChartElement();
    }

    /**
     * Create an instance of {@link ColumnSetElement }
     * 
     */
    public ColumnSetElement createColumnSetElement() {
        return new ColumnSetElement();
    }

    /**
     * Create an instance of {@link ColumnSeriesElement }
     * 
     */
    public ColumnSeriesElement createColumnSeriesElement() {
        return new ColumnSeriesElement();
    }

    /**
     * Create an instance of {@link FormatterSetElement }
     * 
     */
    public FormatterSetElement createFormatterSetElement() {
        return new FormatterSetElement();
    }

    /**
     * Create an instance of {@link LineSetElement }
     * 
     */
    public LineSetElement createLineSetElement() {
        return new LineSetElement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XYChartElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.amdocs.com/dashboard/mobile/XYChart", name = "XYChart")
    public JAXBElement<XYChartElement> createXYChart(XYChartElement value) {
        return new JAXBElement<XYChartElement>(_XYChart_QNAME, XYChartElement.class, null, value);
    }

}
