//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 12:51:18 AM CST 
//


package com.amdocs.dashboard.mobile.xyChart;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for seriesElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="seriesElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="yField" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fillColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fillAlpha" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "seriesElement")
@XmlSeeAlso({
    LineSeriesElement.class,
    ColumnSeriesElement.class
})
public class SeriesElement {

    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected String displayName;
    @XmlAttribute
    protected String yField;
    @XmlAttribute
    protected String fillColor;
    @XmlAttribute
    protected Float fillAlpha;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    public boolean isSetId() {
        return (this.id!= null);
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    public boolean isSetDisplayName() {
        return (this.displayName!= null);
    }

    /**
     * Gets the value of the yField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYField() {
        return yField;
    }

    /**
     * Sets the value of the yField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYField(String value) {
        this.yField = value;
    }

    public boolean isSetYField() {
        return (this.yField!= null);
    }

    /**
     * Gets the value of the fillColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillColor() {
        return fillColor;
    }

    /**
     * Sets the value of the fillColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillColor(String value) {
        this.fillColor = value;
    }

    public boolean isSetFillColor() {
        return (this.fillColor!= null);
    }

    /**
     * Gets the value of the fillAlpha property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getFillAlpha() {
        return fillAlpha;
    }

    /**
     * Sets the value of the fillAlpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFillAlpha(float value) {
        this.fillAlpha = value;
    }

    public boolean isSetFillAlpha() {
        return (this.fillAlpha!= null);
    }

    public void unsetFillAlpha() {
        this.fillAlpha = null;
    }

}
