//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.16 at 02:40:18 PM CDT 
//


package com.amdocs.dashboard.mobile.kpiReport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KpiElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KpiElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="actualField" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="targetField" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="changeField" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="changePctField" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="percentField" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fractionalDigits" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="includeInStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="preference" type="{http://www.amdocs.com/dashboard/mobile/report}KpiPreferenceTypeAttr" default="high" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KpiElement")
public class KpiElement {

    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String actualField;
    @XmlAttribute
    protected String targetField;
    @XmlAttribute
    protected String changeField;
    @XmlAttribute
    protected String changePctField;
    @XmlAttribute
    protected String percentField;
    @XmlAttribute
    protected String type;
    @XmlAttribute
    protected Integer fractionalDigits;
    @XmlAttribute
    protected Boolean includeInStatus;
    @XmlAttribute
    protected KpiPreferenceTypeAttr preference;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

    /**
     * Gets the value of the actualField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualField() {
        return actualField;
    }

    /**
     * Sets the value of the actualField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualField(String value) {
        this.actualField = value;
    }

    public boolean isSetActualField() {
        return (this.actualField!= null);
    }

    /**
     * Gets the value of the targetField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetField() {
        return targetField;
    }

    /**
     * Sets the value of the targetField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetField(String value) {
        this.targetField = value;
    }

    public boolean isSetTargetField() {
        return (this.targetField!= null);
    }

    /**
     * Gets the value of the changeField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeField() {
        return changeField;
    }

    /**
     * Sets the value of the changeField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeField(String value) {
        this.changeField = value;
    }

    public boolean isSetChangeField() {
        return (this.changeField!= null);
    }

    /**
     * Gets the value of the changePctField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangePctField() {
        return changePctField;
    }

    /**
     * Sets the value of the changePctField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangePctField(String value) {
        this.changePctField = value;
    }

    public boolean isSetChangePctField() {
        return (this.changePctField!= null);
    }

    /**
     * Gets the value of the percentField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercentField() {
        return percentField;
    }

    /**
     * Sets the value of the percentField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercentField(String value) {
        this.percentField = value;
    }

    public boolean isSetPercentField() {
        return (this.percentField!= null);
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    public boolean isSetType() {
        return (this.type!= null);
    }

    /**
     * Gets the value of the fractionalDigits property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getFractionalDigits() {
        return fractionalDigits;
    }

    /**
     * Sets the value of the fractionalDigits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFractionalDigits(int value) {
        this.fractionalDigits = value;
    }

    public boolean isSetFractionalDigits() {
        return (this.fractionalDigits!= null);
    }

    public void unsetFractionalDigits() {
        this.fractionalDigits = null;
    }

    /**
     * Gets the value of the includeInStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIncludeInStatus() {
        if (includeInStatus == null) {
            return true;
        } else {
            return includeInStatus;
        }
    }

    /**
     * Sets the value of the includeInStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeInStatus(boolean value) {
        this.includeInStatus = value;
    }

    public boolean isSetIncludeInStatus() {
        return (this.includeInStatus!= null);
    }

    public void unsetIncludeInStatus() {
        this.includeInStatus = null;
    }

    /**
     * Gets the value of the preference property.
     * 
     * @return
     *     possible object is
     *     {@link KpiPreferenceTypeAttr }
     *     
     */
    public KpiPreferenceTypeAttr getPreference() {
        if (preference == null) {
            return KpiPreferenceTypeAttr.HIGH;
        } else {
            return preference;
        }
    }

    /**
     * Sets the value of the preference property.
     * 
     * @param value
     *     allowed object is
     *     {@link KpiPreferenceTypeAttr }
     *     
     */
    public void setPreference(KpiPreferenceTypeAttr value) {
        this.preference = value;
    }

    public boolean isSetPreference() {
        return (this.preference!= null);
    }

}
