//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.14 at 02:00:09 PM CDT 
//


package com.amdocs.dashboard.mobile.kpiReport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MetadataElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MetadataElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="xmlCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="configurationId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cacheLife" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MetadataElement")
public class MetadataElement {

    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected String xmlCode;
    @XmlAttribute
    protected String configurationId;
    @XmlAttribute
    protected Integer cacheLife;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

    /**
     * Gets the value of the xmlCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlCode() {
        return xmlCode;
    }

    /**
     * Sets the value of the xmlCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlCode(String value) {
        this.xmlCode = value;
    }

    public boolean isSetXmlCode() {
        return (this.xmlCode!= null);
    }

    /**
     * Gets the value of the configurationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigurationId() {
        return configurationId;
    }

    /**
     * Sets the value of the configurationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigurationId(String value) {
        this.configurationId = value;
    }

    public boolean isSetConfigurationId() {
        return (this.configurationId!= null);
    }

    /**
     * Gets the value of the cacheLife property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getCacheLife() {
        if (cacheLife == null) {
            return  0;
        } else {
            return cacheLife;
        }
    }

    /**
     * Sets the value of the cacheLife property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCacheLife(int value) {
        this.cacheLife = value;
    }

    public boolean isSetCacheLife() {
        return (this.cacheLife!= null);
    }

    public void unsetCacheLife() {
        this.cacheLife = null;
    }

}
