//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.05 at 05:01:07 PM CDT 
//


package com.amdocs.dashboard.mobile.kpiReport;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.amdocs.dashboard.mobile.kpiReport package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _KpiReport_QNAME = new QName("http://www.amdocs.com/dashboard/mobile/report", "KpiReport");
    private final static QName _Report_QNAME = new QName("http://www.amdocs.com/dashboard/mobile/report", "Report");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.amdocs.dashboard.mobile.kpiReport
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MetadataElement }
     * 
     */
    public MetadataElement createMetadataElement() {
        return new MetadataElement();
    }

    /**
     * Create an instance of {@link ServiceParam }
     * 
     */
    public ServiceParam createServiceParam() {
        return new ServiceParam();
    }

    /**
     * Create an instance of {@link LevelCategoryElement }
     * 
     */
    public LevelCategoryElement createLevelCategoryElement() {
        return new LevelCategoryElement();
    }

    /**
     * Create an instance of {@link ServiceElement }
     * 
     */
    public ServiceElement createServiceElement() {
        return new ServiceElement();
    }

    /**
     * Create an instance of {@link ReportElement }
     * 
     */
    public ReportElement createReportElement() {
        return new ReportElement();
    }

    /**
     * Create an instance of {@link KpiReportElement }
     * 
     */
    public KpiReportElement createKpiReportElement() {
        return new KpiReportElement();
    }

    /**
     * Create an instance of {@link KpiFilterElement }
     * 
     */
    public KpiFilterElement createKpiFilterElement() {
        return new KpiFilterElement();
    }

    /**
     * Create an instance of {@link LevelElement }
     * 
     */
    public LevelElement createLevelElement() {
        return new LevelElement();
    }

    /**
     * Create an instance of {@link DetailViewElement }
     * 
     */
    public DetailViewElement createDetailViewElement() {
        return new DetailViewElement();
    }

    /**
     * Create an instance of {@link KpiElement }
     * 
     */
    public KpiElement createKpiElement() {
        return new KpiElement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KpiReportElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.amdocs.com/dashboard/mobile/report", name = "KpiReport")
    public JAXBElement<KpiReportElement> createKpiReport(KpiReportElement value) {
        return new JAXBElement<KpiReportElement>(_KpiReport_QNAME, KpiReportElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReportElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.amdocs.com/dashboard/mobile/report", name = "Report")
    public JAXBElement<ReportElement> createReport(ReportElement value) {
        return new JAXBElement<ReportElement>(_Report_QNAME, ReportElement.class, null, value);
    }

}
