//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 11:07:47 AM CST 
//


package com.amdocs.dashboard.mobile.kpiReport;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceParamTypeAttr.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ServiceParamTypeAttr">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="string"/>
 *     &lt;enumeration value="number"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ServiceParamTypeAttr")
@XmlEnum
public enum ServiceParamTypeAttr {

    @XmlEnumValue("string")
    STRING("string"),
    @XmlEnumValue("number")
    NUMBER("number");
    private final String value;

    ServiceParamTypeAttr(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServiceParamTypeAttr fromValue(String v) {
        for (ServiceParamTypeAttr c: ServiceParamTypeAttr.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
