//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.04 at 10:45:01 AM CDT 
//


package com.amdocs.dashboard.mobile.grid;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Column complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Column">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dataField" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dataTipField" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="headerLabel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="headerWordWrap" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="type" default="string">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="string"/>
 *             &lt;enumeration value="checkbox"/>
 *             &lt;enumeration value="currency"/>
 *             &lt;enumeration value="date"/>
 *             &lt;enumeration value="datetime"/>
 *             &lt;enumeration value="datestring"/>
 *             &lt;enumeration value="number"/>
 *             &lt;enumeration value="percent"/>
 *             &lt;enumeration value="phone"/>
 *             &lt;enumeration value="zipcode"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="locked" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="securityProfile">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="itemRenderer" default="com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="itemRendererSecurityProfile">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="itemEditor" default="com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="itemEditorSecurityProfile">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="useItemEditorAsItemRenderer">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="headerItemRenderer" default="mx.controls.advancedDataGridClasses.AdvancedDataGridHeaderRenderer">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="click" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="visible" default="true">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="true"/>
 *             &lt;enumeration value="false"/>
 *             &lt;enumeration value="always"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="footerType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="currency"/>
 *             &lt;enumeration value="number"/>
 *             &lt;enumeration value="percent"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="footerFunction">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="avg"/>
 *             &lt;enumeration value="count"/>
 *             &lt;enumeration value="sum"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="footerLabel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="currencySymbol" type="{http://www.w3.org/2001/XMLSchema}string" default="$" />
 *       &lt;attribute name="decimalSeparator" type="{http://www.w3.org/2001/XMLSchema}string" default="," />
 *       &lt;attribute name="digitTypes" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="errorText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fractionalDigits" type="{http://www.w3.org/2001/XMLSchema}int" default="-1" />
 *       &lt;attribute name="groupingPattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="groupingSeparator" type="{http://www.w3.org/2001/XMLSchema}string" default="," />
 *       &lt;attribute name="leadingZero" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="negativeCurrencyFormat" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="negativeSymbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="positiveCurrencyFormat" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="trailingZeros" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="useGrouping" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="includeInExport" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="dateTimePattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="minimum" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="maximum" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="maxChars" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="stepSize" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="snapInterval" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="textAlign">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="center"/>
 *             &lt;enumeration value="left"/>
 *             &lt;enumeration value="right"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="truncateToFit">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="widthInChars" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="heightInLines" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="domainCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="formField" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="formType" default="Label">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="CheckBox"/>
 *             &lt;enumeration value="ComboBox"/>
 *             &lt;enumeration value="DateField"/>
 *             &lt;enumeration value="DropDownList"/>
 *             &lt;enumeration value="Employee"/>
 *             &lt;enumeration value="Label"/>
 *             &lt;enumeration value="NumericStepper"/>
 *             &lt;enumeration value="RadioButton"/>
 *             &lt;enumeration value="SLVFormElement"/>
 *             &lt;enumeration value="TextInput"/>
 *             &lt;enumeration value="TextArea"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="formGroup" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="filterable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="sortable">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="relatedColumns">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="relatedGroupColumns">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Column")
public class Column {

    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected String dataField;
    @XmlAttribute
    protected String dataTipField;
    @XmlAttribute
    protected String headerLabel;
    @XmlAttribute
    protected Boolean headerWordWrap;
    @XmlAttribute
    protected String type;
    @XmlAttribute
    protected Boolean locked;
    @XmlAttribute
    protected Boolean key;
    @XmlAttribute
    protected String securityProfile;
    @XmlAttribute
    protected String itemRenderer;
    @XmlAttribute
    protected String itemRendererSecurityProfile;
    @XmlAttribute
    protected String itemEditor;
    @XmlAttribute
    protected String itemEditorSecurityProfile;
    @XmlAttribute
    protected Boolean useItemEditorAsItemRenderer;
    @XmlAttribute
    protected String headerItemRenderer;
    @XmlAttribute
    protected String click;
    @XmlAttribute
    protected String visible;
    @XmlAttribute
    protected String footerType;
    @XmlAttribute
    protected String footerFunction;
    @XmlAttribute
    protected String footerLabel;
    @XmlAttribute
    protected String currencySymbol;
    @XmlAttribute
    protected String decimalSeparator;
    @XmlAttribute
    protected String digitTypes;
    @XmlAttribute
    protected String errorText;
    @XmlAttribute
    protected Integer fractionalDigits;
    @XmlAttribute
    protected String groupingPattern;
    @XmlAttribute
    protected String groupingSeparator;
    @XmlAttribute
    protected Boolean leadingZero;
    @XmlAttribute
    protected Integer negativeCurrencyFormat;
    @XmlAttribute
    protected String negativeSymbol;
    @XmlAttribute
    protected Integer positiveCurrencyFormat;
    @XmlAttribute
    protected Boolean trailingZeros;
    @XmlAttribute
    protected Boolean useGrouping;
    @XmlAttribute
    protected Boolean includeInExport;
    @XmlAttribute
    protected String dateTimePattern;
    @XmlAttribute
    protected BigDecimal minimum;
    @XmlAttribute
    protected BigDecimal maximum;
    @XmlAttribute
    protected Integer maxChars;
    @XmlAttribute
    protected BigDecimal stepSize;
    @XmlAttribute
    protected BigDecimal snapInterval;
    @XmlAttribute
    protected String textAlign;
    @XmlAttribute
    protected Boolean truncateToFit;
    @XmlAttribute
    protected Integer width;
    @XmlAttribute
    protected Integer widthInChars;
    @XmlAttribute
    protected Integer heightInLines;
    @XmlAttribute
    protected Boolean editable;
    @XmlAttribute
    protected Integer size;
    @XmlAttribute
    protected Boolean required;
    @XmlAttribute
    protected String domainCode;
    @XmlAttribute
    protected String formField;
    @XmlAttribute
    protected String formType;
    @XmlAttribute
    protected String formGroup;
    @XmlAttribute
    protected Boolean filterable;
    @XmlAttribute
    protected Boolean sortable;
    @XmlAttribute
    protected String relatedColumns;
    @XmlAttribute
    protected String relatedGroupColumns;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    public boolean isSetId() {
        return (this.id!= null);
    }

    /**
     * Gets the value of the dataField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataField() {
        return dataField;
    }

    /**
     * Sets the value of the dataField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataField(String value) {
        this.dataField = value;
    }

    public boolean isSetDataField() {
        return (this.dataField!= null);
    }

    /**
     * Gets the value of the dataTipField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataTipField() {
        return dataTipField;
    }

    /**
     * Sets the value of the dataTipField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataTipField(String value) {
        this.dataTipField = value;
    }

    public boolean isSetDataTipField() {
        return (this.dataTipField!= null);
    }

    /**
     * Gets the value of the headerLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeaderLabel() {
        return headerLabel;
    }

    /**
     * Sets the value of the headerLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeaderLabel(String value) {
        this.headerLabel = value;
    }

    public boolean isSetHeaderLabel() {
        return (this.headerLabel!= null);
    }

    /**
     * Gets the value of the headerWordWrap property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHeaderWordWrap() {
        return headerWordWrap;
    }

    /**
     * Sets the value of the headerWordWrap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHeaderWordWrap(boolean value) {
        this.headerWordWrap = value;
    }

    public boolean isSetHeaderWordWrap() {
        return (this.headerWordWrap!= null);
    }

    public void unsetHeaderWordWrap() {
        this.headerWordWrap = null;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "string";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    public boolean isSetType() {
        return (this.type!= null);
    }

    /**
     * Gets the value of the locked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLocked() {
        return locked;
    }

    /**
     * Sets the value of the locked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLocked(boolean value) {
        this.locked = value;
    }

    public boolean isSetLocked() {
        return (this.locked!= null);
    }

    public void unsetLocked() {
        this.locked = null;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKey(boolean value) {
        this.key = value;
    }

    public boolean isSetKey() {
        return (this.key!= null);
    }

    public void unsetKey() {
        this.key = null;
    }

    /**
     * Gets the value of the securityProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityProfile() {
        return securityProfile;
    }

    /**
     * Sets the value of the securityProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityProfile(String value) {
        this.securityProfile = value;
    }

    public boolean isSetSecurityProfile() {
        return (this.securityProfile!= null);
    }

    /**
     * Gets the value of the itemRenderer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemRenderer() {
        if (itemRenderer == null) {
            return "com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer";
        } else {
            return itemRenderer;
        }
    }

    /**
     * Sets the value of the itemRenderer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemRenderer(String value) {
        this.itemRenderer = value;
    }

    public boolean isSetItemRenderer() {
        return (this.itemRenderer!= null);
    }

    /**
     * Gets the value of the itemRendererSecurityProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemRendererSecurityProfile() {
        return itemRendererSecurityProfile;
    }

    /**
     * Sets the value of the itemRendererSecurityProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemRendererSecurityProfile(String value) {
        this.itemRendererSecurityProfile = value;
    }

    public boolean isSetItemRendererSecurityProfile() {
        return (this.itemRendererSecurityProfile!= null);
    }

    /**
     * Gets the value of the itemEditor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemEditor() {
        if (itemEditor == null) {
            return "com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer";
        } else {
            return itemEditor;
        }
    }

    /**
     * Sets the value of the itemEditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemEditor(String value) {
        this.itemEditor = value;
    }

    public boolean isSetItemEditor() {
        return (this.itemEditor!= null);
    }

    /**
     * Gets the value of the itemEditorSecurityProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemEditorSecurityProfile() {
        return itemEditorSecurityProfile;
    }

    /**
     * Sets the value of the itemEditorSecurityProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemEditorSecurityProfile(String value) {
        this.itemEditorSecurityProfile = value;
    }

    public boolean isSetItemEditorSecurityProfile() {
        return (this.itemEditorSecurityProfile!= null);
    }

    /**
     * Gets the value of the useItemEditorAsItemRenderer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseItemEditorAsItemRenderer() {
        return useItemEditorAsItemRenderer;
    }

    /**
     * Sets the value of the useItemEditorAsItemRenderer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseItemEditorAsItemRenderer(boolean value) {
        this.useItemEditorAsItemRenderer = value;
    }

    public boolean isSetUseItemEditorAsItemRenderer() {
        return (this.useItemEditorAsItemRenderer!= null);
    }

    public void unsetUseItemEditorAsItemRenderer() {
        this.useItemEditorAsItemRenderer = null;
    }

    /**
     * Gets the value of the headerItemRenderer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeaderItemRenderer() {
        if (headerItemRenderer == null) {
            return "mx.controls.advancedDataGridClasses.AdvancedDataGridHeaderRenderer";
        } else {
            return headerItemRenderer;
        }
    }

    /**
     * Sets the value of the headerItemRenderer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeaderItemRenderer(String value) {
        this.headerItemRenderer = value;
    }

    public boolean isSetHeaderItemRenderer() {
        return (this.headerItemRenderer!= null);
    }

    /**
     * Gets the value of the click property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClick() {
        return click;
    }

    /**
     * Sets the value of the click property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClick(String value) {
        this.click = value;
    }

    public boolean isSetClick() {
        return (this.click!= null);
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisible() {
        if (visible == null) {
            return "true";
        } else {
            return visible;
        }
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisible(String value) {
        this.visible = value;
    }

    public boolean isSetVisible() {
        return (this.visible!= null);
    }

    /**
     * Gets the value of the footerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFooterType() {
        return footerType;
    }

    /**
     * Sets the value of the footerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFooterType(String value) {
        this.footerType = value;
    }

    public boolean isSetFooterType() {
        return (this.footerType!= null);
    }

    /**
     * Gets the value of the footerFunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFooterFunction() {
        return footerFunction;
    }

    /**
     * Sets the value of the footerFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFooterFunction(String value) {
        this.footerFunction = value;
    }

    public boolean isSetFooterFunction() {
        return (this.footerFunction!= null);
    }

    /**
     * Gets the value of the footerLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFooterLabel() {
        return footerLabel;
    }

    /**
     * Sets the value of the footerLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFooterLabel(String value) {
        this.footerLabel = value;
    }

    public boolean isSetFooterLabel() {
        return (this.footerLabel!= null);
    }

    /**
     * Gets the value of the currencySymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencySymbol() {
        if (currencySymbol == null) {
            return "$";
        } else {
            return currencySymbol;
        }
    }

    /**
     * Sets the value of the currencySymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencySymbol(String value) {
        this.currencySymbol = value;
    }

    public boolean isSetCurrencySymbol() {
        return (this.currencySymbol!= null);
    }

    /**
     * Gets the value of the decimalSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecimalSeparator() {
        if (decimalSeparator == null) {
            return ",";
        } else {
            return decimalSeparator;
        }
    }

    /**
     * Sets the value of the decimalSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecimalSeparator(String value) {
        this.decimalSeparator = value;
    }

    public boolean isSetDecimalSeparator() {
        return (this.decimalSeparator!= null);
    }

    /**
     * Gets the value of the digitTypes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigitTypes() {
        return digitTypes;
    }

    /**
     * Sets the value of the digitTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigitTypes(String value) {
        this.digitTypes = value;
    }

    public boolean isSetDigitTypes() {
        return (this.digitTypes!= null);
    }

    /**
     * Gets the value of the errorText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorText() {
        return errorText;
    }

    /**
     * Sets the value of the errorText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorText(String value) {
        this.errorText = value;
    }

    public boolean isSetErrorText() {
        return (this.errorText!= null);
    }

    /**
     * Gets the value of the fractionalDigits property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getFractionalDigits() {
        if (fractionalDigits == null) {
            return -1;
        } else {
            return fractionalDigits;
        }
    }

    /**
     * Sets the value of the fractionalDigits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFractionalDigits(int value) {
        this.fractionalDigits = value;
    }

    public boolean isSetFractionalDigits() {
        return (this.fractionalDigits!= null);
    }

    public void unsetFractionalDigits() {
        this.fractionalDigits = null;
    }

    /**
     * Gets the value of the groupingPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupingPattern() {
        return groupingPattern;
    }

    /**
     * Sets the value of the groupingPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupingPattern(String value) {
        this.groupingPattern = value;
    }

    public boolean isSetGroupingPattern() {
        return (this.groupingPattern!= null);
    }

    /**
     * Gets the value of the groupingSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupingSeparator() {
        if (groupingSeparator == null) {
            return ",";
        } else {
            return groupingSeparator;
        }
    }

    /**
     * Sets the value of the groupingSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupingSeparator(String value) {
        this.groupingSeparator = value;
    }

    public boolean isSetGroupingSeparator() {
        return (this.groupingSeparator!= null);
    }

    /**
     * Gets the value of the leadingZero property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLeadingZero() {
        return leadingZero;
    }

    /**
     * Sets the value of the leadingZero property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLeadingZero(boolean value) {
        this.leadingZero = value;
    }

    public boolean isSetLeadingZero() {
        return (this.leadingZero!= null);
    }

    public void unsetLeadingZero() {
        this.leadingZero = null;
    }

    /**
     * Gets the value of the negativeCurrencyFormat property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getNegativeCurrencyFormat() {
        return negativeCurrencyFormat;
    }

    /**
     * Sets the value of the negativeCurrencyFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNegativeCurrencyFormat(int value) {
        this.negativeCurrencyFormat = value;
    }

    public boolean isSetNegativeCurrencyFormat() {
        return (this.negativeCurrencyFormat!= null);
    }

    public void unsetNegativeCurrencyFormat() {
        this.negativeCurrencyFormat = null;
    }

    /**
     * Gets the value of the negativeSymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNegativeSymbol() {
        return negativeSymbol;
    }

    /**
     * Sets the value of the negativeSymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNegativeSymbol(String value) {
        this.negativeSymbol = value;
    }

    public boolean isSetNegativeSymbol() {
        return (this.negativeSymbol!= null);
    }

    /**
     * Gets the value of the positiveCurrencyFormat property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getPositiveCurrencyFormat() {
        return positiveCurrencyFormat;
    }

    /**
     * Sets the value of the positiveCurrencyFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPositiveCurrencyFormat(int value) {
        this.positiveCurrencyFormat = value;
    }

    public boolean isSetPositiveCurrencyFormat() {
        return (this.positiveCurrencyFormat!= null);
    }

    public void unsetPositiveCurrencyFormat() {
        this.positiveCurrencyFormat = null;
    }

    /**
     * Gets the value of the trailingZeros property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTrailingZeros() {
        return trailingZeros;
    }

    /**
     * Sets the value of the trailingZeros property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTrailingZeros(boolean value) {
        this.trailingZeros = value;
    }

    public boolean isSetTrailingZeros() {
        return (this.trailingZeros!= null);
    }

    public void unsetTrailingZeros() {
        this.trailingZeros = null;
    }

    /**
     * Gets the value of the useGrouping property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseGrouping() {
        if (useGrouping == null) {
            return true;
        } else {
            return useGrouping;
        }
    }

    /**
     * Sets the value of the useGrouping property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseGrouping(boolean value) {
        this.useGrouping = value;
    }

    public boolean isSetUseGrouping() {
        return (this.useGrouping!= null);
    }

    public void unsetUseGrouping() {
        this.useGrouping = null;
    }

    /**
     * Gets the value of the includeInExport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIncludeInExport() {
        if (includeInExport == null) {
            return true;
        } else {
            return includeInExport;
        }
    }

    /**
     * Sets the value of the includeInExport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeInExport(boolean value) {
        this.includeInExport = value;
    }

    public boolean isSetIncludeInExport() {
        return (this.includeInExport!= null);
    }

    public void unsetIncludeInExport() {
        this.includeInExport = null;
    }

    /**
     * Gets the value of the dateTimePattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateTimePattern() {
        return dateTimePattern;
    }

    /**
     * Sets the value of the dateTimePattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateTimePattern(String value) {
        this.dateTimePattern = value;
    }

    public boolean isSetDateTimePattern() {
        return (this.dateTimePattern!= null);
    }

    /**
     * Gets the value of the minimum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinimum() {
        return minimum;
    }

    /**
     * Sets the value of the minimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinimum(BigDecimal value) {
        this.minimum = value;
    }

    public boolean isSetMinimum() {
        return (this.minimum!= null);
    }

    /**
     * Gets the value of the maximum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaximum() {
        return maximum;
    }

    /**
     * Sets the value of the maximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaximum(BigDecimal value) {
        this.maximum = value;
    }

    public boolean isSetMaximum() {
        return (this.maximum!= null);
    }

    /**
     * Gets the value of the maxChars property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxChars() {
        return maxChars;
    }

    /**
     * Sets the value of the maxChars property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxChars(int value) {
        this.maxChars = value;
    }

    public boolean isSetMaxChars() {
        return (this.maxChars!= null);
    }

    public void unsetMaxChars() {
        this.maxChars = null;
    }

    /**
     * Gets the value of the stepSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStepSize() {
        return stepSize;
    }

    /**
     * Sets the value of the stepSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStepSize(BigDecimal value) {
        this.stepSize = value;
    }

    public boolean isSetStepSize() {
        return (this.stepSize!= null);
    }

    /**
     * Gets the value of the snapInterval property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSnapInterval() {
        return snapInterval;
    }

    /**
     * Sets the value of the snapInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSnapInterval(BigDecimal value) {
        this.snapInterval = value;
    }

    public boolean isSetSnapInterval() {
        return (this.snapInterval!= null);
    }

    /**
     * Gets the value of the textAlign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextAlign() {
        return textAlign;
    }

    /**
     * Sets the value of the textAlign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextAlign(String value) {
        this.textAlign = value;
    }

    public boolean isSetTextAlign() {
        return (this.textAlign!= null);
    }

    /**
     * Gets the value of the truncateToFit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTruncateToFit() {
        return truncateToFit;
    }

    /**
     * Sets the value of the truncateToFit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTruncateToFit(boolean value) {
        this.truncateToFit = value;
    }

    public boolean isSetTruncateToFit() {
        return (this.truncateToFit!= null);
    }

    public void unsetTruncateToFit() {
        this.truncateToFit = null;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWidth(int value) {
        this.width = value;
    }

    public boolean isSetWidth() {
        return (this.width!= null);
    }

    public void unsetWidth() {
        this.width = null;
    }

    /**
     * Gets the value of the widthInChars property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getWidthInChars() {
        return widthInChars;
    }

    /**
     * Sets the value of the widthInChars property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWidthInChars(int value) {
        this.widthInChars = value;
    }

    public boolean isSetWidthInChars() {
        return (this.widthInChars!= null);
    }

    public void unsetWidthInChars() {
        this.widthInChars = null;
    }

    /**
     * Gets the value of the heightInLines property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getHeightInLines() {
        return heightInLines;
    }

    /**
     * Sets the value of the heightInLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHeightInLines(int value) {
        this.heightInLines = value;
    }

    public boolean isSetHeightInLines() {
        return (this.heightInLines!= null);
    }

    public void unsetHeightInLines() {
        this.heightInLines = null;
    }

    /**
     * Gets the value of the editable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEditable() {
        return editable;
    }

    /**
     * Sets the value of the editable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEditable(boolean value) {
        this.editable = value;
    }

    public boolean isSetEditable() {
        return (this.editable!= null);
    }

    public void unsetEditable() {
        this.editable = null;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSize(int value) {
        this.size = value;
    }

    public boolean isSetSize() {
        return (this.size!= null);
    }

    public void unsetSize() {
        this.size = null;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequired(boolean value) {
        this.required = value;
    }

    public boolean isSetRequired() {
        return (this.required!= null);
    }

    public void unsetRequired() {
        this.required = null;
    }

    /**
     * Gets the value of the domainCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainCode() {
        return domainCode;
    }

    /**
     * Sets the value of the domainCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainCode(String value) {
        this.domainCode = value;
    }

    public boolean isSetDomainCode() {
        return (this.domainCode!= null);
    }

    /**
     * Gets the value of the formField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormField() {
        return formField;
    }

    /**
     * Sets the value of the formField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormField(String value) {
        this.formField = value;
    }

    public boolean isSetFormField() {
        return (this.formField!= null);
    }

    /**
     * Gets the value of the formType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormType() {
        if (formType == null) {
            return "Label";
        } else {
            return formType;
        }
    }

    /**
     * Sets the value of the formType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormType(String value) {
        this.formType = value;
    }

    public boolean isSetFormType() {
        return (this.formType!= null);
    }

    /**
     * Gets the value of the formGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormGroup() {
        return formGroup;
    }

    /**
     * Sets the value of the formGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormGroup(String value) {
        this.formGroup = value;
    }

    public boolean isSetFormGroup() {
        return (this.formGroup!= null);
    }

    /**
     * Gets the value of the filterable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isFilterable() {
        return filterable;
    }

    /**
     * Sets the value of the filterable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFilterable(boolean value) {
        this.filterable = value;
    }

    public boolean isSetFilterable() {
        return (this.filterable!= null);
    }

    public void unsetFilterable() {
        this.filterable = null;
    }

    /**
     * Gets the value of the sortable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSortable() {
        return sortable;
    }

    /**
     * Sets the value of the sortable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSortable(boolean value) {
        this.sortable = value;
    }

    public boolean isSetSortable() {
        return (this.sortable!= null);
    }

    public void unsetSortable() {
        this.sortable = null;
    }

    /**
     * Gets the value of the relatedColumns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedColumns() {
        return relatedColumns;
    }

    /**
     * Sets the value of the relatedColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedColumns(String value) {
        this.relatedColumns = value;
    }

    public boolean isSetRelatedColumns() {
        return (this.relatedColumns!= null);
    }

    /**
     * Gets the value of the relatedGroupColumns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedGroupColumns() {
        return relatedGroupColumns;
    }

    /**
     * Sets the value of the relatedGroupColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedGroupColumns(String value) {
        this.relatedGroupColumns = value;
    }

    public boolean isSetRelatedGroupColumns() {
        return (this.relatedGroupColumns!= null);
    }

}
