//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.19 at 11:38:58 AM CST 
//


package com.amdocs.dashboard.mobile.grid;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomDataGrid complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomDataGrid">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid}Column" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid}GroupedColumns" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="allowLockedColumnChange" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="allowShowFooterChange" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="lockedColumnCount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="showFooter" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="showFilters" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="defaultItemRenderer" default="com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="defaultItemEditor" default="com.amdocs.dashboard.customDataGrid.CustomDataGridItemEditor">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomDataGrid", propOrder = {
    "columns",
    "groupedColumns"
})
public class CustomDataGrid {

    @XmlElement(name = "Column", required = true)
    protected List<Column> columns;
    @XmlElement(name = "GroupedColumns")
    protected GroupedColumns groupedColumns;
    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected String title;
    @XmlAttribute
    protected Integer version;
    @XmlAttribute
    protected Boolean allowLockedColumnChange;
    @XmlAttribute
    protected Boolean allowShowFooterChange;
    @XmlAttribute
    protected Integer lockedColumnCount;
    @XmlAttribute
    protected Boolean showFooter;
    @XmlAttribute
    protected Boolean showFilters;
    @XmlAttribute
    protected String defaultItemRenderer;
    @XmlAttribute
    protected String defaultItemEditor;

    /**
     * Gets the value of the columns property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the columns property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColumns().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Column }
     * 
     * 
     */
    public List<Column> getColumns() {
        if (columns == null) {
            columns = new ArrayList<Column>();
        }
        return this.columns;
    }

    public boolean isSetColumns() {
        return ((this.columns!= null)&&(!this.columns.isEmpty()));
    }

    public void unsetColumns() {
        this.columns = null;
    }

    /**
     * Gets the value of the groupedColumns property.
     * 
     * @return
     *     possible object is
     *     {@link GroupedColumns }
     *     
     */
    public GroupedColumns getGroupedColumns() {
        return groupedColumns;
    }

    /**
     * Sets the value of the groupedColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupedColumns }
     *     
     */
    public void setGroupedColumns(GroupedColumns value) {
        this.groupedColumns = value;
    }

    public boolean isSetGroupedColumns() {
        return (this.groupedColumns!= null);
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    public boolean isSetId() {
        return (this.id!= null);
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    public boolean isSetTitle() {
        return (this.title!= null);
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVersion(int value) {
        this.version = value;
    }

    public boolean isSetVersion() {
        return (this.version!= null);
    }

    public void unsetVersion() {
        this.version = null;
    }

    /**
     * Gets the value of the allowLockedColumnChange property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowLockedColumnChange() {
        return allowLockedColumnChange;
    }

    /**
     * Sets the value of the allowLockedColumnChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowLockedColumnChange(boolean value) {
        this.allowLockedColumnChange = value;
    }

    public boolean isSetAllowLockedColumnChange() {
        return (this.allowLockedColumnChange!= null);
    }

    public void unsetAllowLockedColumnChange() {
        this.allowLockedColumnChange = null;
    }

    /**
     * Gets the value of the allowShowFooterChange property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowShowFooterChange() {
        return allowShowFooterChange;
    }

    /**
     * Sets the value of the allowShowFooterChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowShowFooterChange(boolean value) {
        this.allowShowFooterChange = value;
    }

    public boolean isSetAllowShowFooterChange() {
        return (this.allowShowFooterChange!= null);
    }

    public void unsetAllowShowFooterChange() {
        this.allowShowFooterChange = null;
    }

    /**
     * Gets the value of the lockedColumnCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getLockedColumnCount() {
        return lockedColumnCount;
    }

    /**
     * Sets the value of the lockedColumnCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLockedColumnCount(int value) {
        this.lockedColumnCount = value;
    }

    public boolean isSetLockedColumnCount() {
        return (this.lockedColumnCount!= null);
    }

    public void unsetLockedColumnCount() {
        this.lockedColumnCount = null;
    }

    /**
     * Gets the value of the showFooter property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowFooter() {
        return showFooter;
    }

    /**
     * Sets the value of the showFooter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowFooter(boolean value) {
        this.showFooter = value;
    }

    public boolean isSetShowFooter() {
        return (this.showFooter!= null);
    }

    public void unsetShowFooter() {
        this.showFooter = null;
    }

    /**
     * Gets the value of the showFilters property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowFilters() {
        return showFilters;
    }

    /**
     * Sets the value of the showFilters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowFilters(boolean value) {
        this.showFilters = value;
    }

    public boolean isSetShowFilters() {
        return (this.showFilters!= null);
    }

    public void unsetShowFilters() {
        this.showFilters = null;
    }

    /**
     * Gets the value of the defaultItemRenderer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultItemRenderer() {
        if (defaultItemRenderer == null) {
            return "com.amdocs.dashboard.customDataGrid.CustomDataGridItemRenderer";
        } else {
            return defaultItemRenderer;
        }
    }

    /**
     * Sets the value of the defaultItemRenderer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultItemRenderer(String value) {
        this.defaultItemRenderer = value;
    }

    public boolean isSetDefaultItemRenderer() {
        return (this.defaultItemRenderer!= null);
    }

    /**
     * Gets the value of the defaultItemEditor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultItemEditor() {
        if (defaultItemEditor == null) {
            return "com.amdocs.dashboard.customDataGrid.CustomDataGridItemEditor";
        } else {
            return defaultItemEditor;
        }
    }

    /**
     * Sets the value of the defaultItemEditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultItemEditor(String value) {
        this.defaultItemEditor = value;
    }

    public boolean isSetDefaultItemEditor() {
        return (this.defaultItemEditor!= null);
    }

}
