//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.04 at 10:45:01 AM CDT 
//


package com.amdocs.dashboard.mobile.grid;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.amdocs.dashboard.mobile.grid package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Column_QNAME = new QName("http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid", "Column");
    private final static QName _CustomDataGrid_QNAME = new QName("http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid", "CustomDataGrid");
    private final static QName _GroupedColumns_QNAME = new QName("http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid", "GroupedColumns");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.amdocs.dashboard.mobile.grid
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomDataGrid }
     * 
     */
    public CustomDataGrid createCustomDataGrid() {
        return new CustomDataGrid();
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link GroupedColumns }
     * 
     */
    public GroupedColumns createGroupedColumns() {
        return new GroupedColumns();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Column }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid", name = "Column")
    public JAXBElement<Column> createColumn(Column value) {
        return new JAXBElement<Column>(_Column_QNAME, Column.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomDataGrid }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid", name = "CustomDataGrid")
    public JAXBElement<CustomDataGrid> createCustomDataGrid(CustomDataGrid value) {
        return new JAXBElement<CustomDataGrid>(_CustomDataGrid_QNAME, CustomDataGrid.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupedColumns }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://amdocs.com/flex/dashboard/customDataGrid/CustomDataGrid", name = "GroupedColumns")
    public JAXBElement<GroupedColumns> createGroupedColumns(GroupedColumns value) {
        return new JAXBElement<GroupedColumns>(_GroupedColumns_QNAME, GroupedColumns.class, null, value);
    }

}
