//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.15 at 09:44:39 PM CST 
//


package com.amdocs.dashboard.mobile.assets;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssetElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssetElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="param" type="{http://www.amdocs.com/dashboard/mobile}ParamElement" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="cacheLife" type="{http://www.amdocs.com/dashboard/mobile}CacheLifeAttribute" default="3600" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="serviceType" type="{http://www.amdocs.com/dashboard/mobile}ServiceTypeAttribute" default="mobileProxy" />
 *       &lt;attribute name="serviceName" type="{http://www.amdocs.com/dashboard/mobile}ServiceNameAttribute" default="getBase64Image" />
 *       &lt;attribute name="type" type="{http://www.amdocs.com/dashboard/mobile}AssetTypeAttribute" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssetElement", propOrder = {
    "params"
})
public class AssetElement {

    @XmlElement(name = "param")
    protected List<ParamElement> params;
    @XmlAttribute
    protected Long cacheLife;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected ServiceTypeAttribute serviceType;
    @XmlAttribute
    protected String serviceName;
    @XmlAttribute
    protected AssetTypeAttribute type;
    @XmlAttribute
    protected Integer version;

    /**
     * Gets the value of the params property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the params property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamElement }
     * 
     * 
     */
    public List<ParamElement> getParams() {
        if (params == null) {
            params = new ArrayList<ParamElement>();
        }
        return this.params;
    }

    public boolean isSetParams() {
        return ((this.params!= null)&&(!this.params.isEmpty()));
    }

    public void unsetParams() {
        this.params = null;
    }

    /**
     * Gets the value of the cacheLife property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getCacheLife() {
        if (cacheLife == null) {
            return  3600L;
        } else {
            return cacheLife;
        }
    }

    /**
     * Sets the value of the cacheLife property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCacheLife(long value) {
        this.cacheLife = value;
    }

    public boolean isSetCacheLife() {
        return (this.cacheLife!= null);
    }

    public void unsetCacheLife() {
        this.cacheLife = null;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceTypeAttribute }
     *     
     */
    public ServiceTypeAttribute getServiceType() {
        if (serviceType == null) {
            return ServiceTypeAttribute.MOBILE_PROXY;
        } else {
            return serviceType;
        }
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceTypeAttribute }
     *     
     */
    public void setServiceType(ServiceTypeAttribute value) {
        this.serviceType = value;
    }

    public boolean isSetServiceType() {
        return (this.serviceType!= null);
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        if (serviceName == null) {
            return "getBase64Image";
        } else {
            return serviceName;
        }
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    public boolean isSetServiceName() {
        return (this.serviceName!= null);
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link AssetTypeAttribute }
     *     
     */
    public AssetTypeAttribute getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetTypeAttribute }
     *     
     */
    public void setType(AssetTypeAttribute value) {
        this.type = value;
    }

    public boolean isSetType() {
        return (this.type!= null);
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVersion(int value) {
        this.version = value;
    }

    public boolean isSetVersion() {
        return (this.version!= null);
    }

    public void unsetVersion() {
        this.version = null;
    }

}
