//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.15 at 09:44:39 PM CST 
//


package com.amdocs.dashboard.mobile.assets;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceTypeAttribute.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ServiceTypeAttribute">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="localStorage"/>
 *     &lt;enumeration value="mobileProxy"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ServiceTypeAttribute")
@XmlEnum
public enum ServiceTypeAttribute {

    @XmlEnumValue("localStorage")
    LOCAL_STORAGE("localStorage"),
    @XmlEnumValue("mobileProxy")
    MOBILE_PROXY("mobileProxy");
    private final String value;

    ServiceTypeAttribute(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServiceTypeAttribute fromValue(String v) {
        for (ServiceTypeAttribute c: ServiceTypeAttribute.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
