select CUSTOMER.CUSTOMER_ID, 
       LISTING.FINDING_NAME,
       substr(HBD, 4, 2) as STATE,
       CONTACT.E_MAIL_ADDRESS
  from CUSTOMER, LISTING, CONTACT
 where EPROOF_IND = 'Y'
   and DERIVED_CUST_IND = '0'
   and CUSTOMER.MAIN_MAIN_LISTING_ID = LISTING.listing_id(+)
   and LISTING.LAST_VERSION_IND(+) = 'Y'
   and CUSTOMER.CONTACT_ID = CONTACT.CONTACT_ID